const IMAGES = {
  pic1: require("./resume.png"),
  pic2: require("./Calc.png"),
  pic3: require("./ToDo.png"),
  pic4: require("./Blog.png"),
  pic5: require("./PNE.jpg"),
  pic6: require("./GM.jpg"),
  pic7: require("./weather.png"),
  pic8: require("./portfolio.png"),
  pic9: require("./reading.png"),
  pic10: require("./travel.png"),
  pic11: require("./instagram.png"),
  pic12: require("./blackBook.png"),
  pic13: require("./tech-fansite.png"),
  pic14: require("./banana-fansite.png"),
  pic15: require("./electron-gridmaster.png"),
  pic16: require("./Release-notes-app.png"),
  pic17: require("./ruby-blog.png"),
  pic18: require("./new-weather.png"),
  pic19: require("./recipes.png"),
  pic20: require("./ada-task-list.png"),
  pic21: require("./inspo-board.png"),
  pic22: require("./financial-planner.png"),
  pic23: require("./project_notes.png"),
  pic24: require("./project_validator.png"),
  pic25: require("./work_tracker.png"),
};

export default IMAGES;
